-- ===== Players =====
INSERT INTO players (id, name) VALUES (1,'Pupa');
INSERT INTO players (id, name) VALUES (2,'Lupa');
INSERT INTO players (id, name) VALUES (3,'Tupa');
INSERT INTO players (id, name) VALUES (4,'Rupa');
INSERT INTO players (id, name) VALUES (5,'Supa');
INSERT INTO players (id, name) VALUES (6,'Dupa');
INSERT INTO players (id, name) VALUES (7,'Pupa Jr');
INSERT INTO players (id, name) VALUES (8,'Pupa II');
INSERT INTO players (id, name) VALUES (9,'Lupa Jr');
INSERT INTO players (id, name) VALUES (10,'Lupin');
INSERT INTO players (id, name) VALUES (11,'Rupa Khan');
INSERT INTO players (id, name) VALUES (12,'Tupa Lupa');
INSERT INTO players (id, name) VALUES (13,'Alex');
INSERT INTO players (id, name) VALUES (14,'Alexander');
INSERT INTO players (id, name) VALUES (15,'Alexa');
INSERT INTO players (id, name) VALUES (16,'Aleksey');
INSERT INTO players (id, name) VALUES (17,'John');
INSERT INTO players (id, name) VALUES (18,'Johnny');
INSERT INTO players (id, name) VALUES (19,'Jon');
INSERT INTO players (id, name) VALUES (20,'Jonathan');
INSERT INTO players (id, name) VALUES (21,'Sara');
INSERT INTO players (id, name) VALUES (22,'Sarah');
INSERT INTO players (id, name) VALUES (23,'Zara');
INSERT INTO players (id, name) VALUES (24,'Lara');
INSERT INTO players (id, name) VALUES (25,'Kara');
INSERT INTO players (id, name) VALUES (26,'Farah');
INSERT INTO players (id, name) VALUES (27,'Farruh');
INSERT INTO players (id, name) VALUES (28,'Arman');
INSERT INTO players (id, name) VALUES (29,'Aruzhan');
INSERT INTO players (id, name) VALUES (30,'Arlan');
INSERT INTO players (id, name) VALUES (31,'Aruzhan K.');
INSERT INTO players (id, name) VALUES (32,'Arman A.');
INSERT INTO players (id, name) VALUES (33,'Arman Jr');
INSERT INTO players (id, name) VALUES (34,'Alikhan');
INSERT INTO players (id, name) VALUES (35,'Ali');

-- ===== Matches (33) =====
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (1, 1, 2, 1);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (2, 3, 4, 3);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (3, 5, 6, 5);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (4, 7, 8, 7);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (5, 9, 10, 9);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (6, 11, 12, 11);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (7, 13, 14, 13);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (8, 15, 16, 15);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (9, 17, 18, 18);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (10, 19, 20, 20);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (11, 21, 22, 21);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (12, 23, 24, 24);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (13, 25, 26, 26);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (14, 27, 28, 27);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (15, 29, 30, 30);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (16, 31, 32, 32);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (17, 33, 34, 33);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (18, 35, 1, 1);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (19, 2, 3, 2);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (20, 4, 5, 5);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (21, 6, 7, 6);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (22, 8, 9, 8);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (23, 10, 11, 10);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (24, 12, 13, 12);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (25, 14, 15, 15);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (26, 16, 17, 17);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (27, 18, 19, 18);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (28, 20, 21, 21);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (29, 22, 23, 22);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (30, 24, 25, 24);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (31, 26, 27, 27);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (32, 28, 29, 28);
INSERT INTO MATCHES (id, player1_id, player2_id, winner_id) VALUES (33, 30, 31, 30);
